// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	vector "arc-homework/space-game/moving/vector"
)

// Movable is an autogenerated mock type for the Movable type
type Movable struct {
	mock.Mock
}

// GetPosition provides a mock function with given fields: ctx
func (_m *Movable) GetPosition(ctx context.Context) (vector.Vector, error) {
	ret := _m.Called(ctx)

	var r0 vector.Vector
	if rf, ok := ret.Get(0).(func(context.Context) vector.Vector); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(vector.Vector)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVelocity provides a mock function with given fields: ctx
func (_m *Movable) GetVelocity(ctx context.Context) (vector.Vector, error) {
	ret := _m.Called(ctx)

	var r0 vector.Vector
	if rf, ok := ret.Get(0).(func(context.Context) vector.Vector); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(vector.Vector)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetPosition provides a mock function with given fields: ctx, v
func (_m *Movable) SetPosition(ctx context.Context, v vector.Vector) (vector.Vector, error) {
	ret := _m.Called(ctx, v)

	var r0 vector.Vector
	if rf, ok := ret.Get(0).(func(context.Context, vector.Vector) vector.Vector); ok {
		r0 = rf(ctx, v)
	} else {
		r0 = ret.Get(0).(vector.Vector)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, vector.Vector) error); ok {
		r1 = rf(ctx, v)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetVelocity provides a mock function with given fields: ctx, v
func (_m *Movable) SetVelocity(ctx context.Context, v vector.Vector) (vector.Vector, error) {
	ret := _m.Called(ctx, v)

	var r0 vector.Vector
	if rf, ok := ret.Get(0).(func(context.Context, vector.Vector) vector.Vector); ok {
		r0 = rf(ctx, v)
	} else {
		r0 = ret.Get(0).(vector.Vector)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, vector.Vector) error); ok {
		r1 = rf(ctx, v)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMovable interface {
	mock.TestingT
	Cleanup(func())
}

// NewMovable creates a new instance of Movable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMovable(t mockConstructorTestingTNewMovable) *Movable {
	mock := &Movable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
